Fix link clicking
No response to clicking on a link, logs have many errors, such as;

Traceback (most recent call last):
  File "chat/box.py", line 167, in __event_after_cb
    for tag in iter_tags.get_tags():
AttributeError: '_ResultTuple' object has no attribute 'get_tags'

Upstream intentionally broke [1] the API for
Gtk.TextView.get_iter_at_location in gtk+ a3a5cf1 ("text view: Improve tag
pointer tracking") as of Gtk+ 3.19.9.

Add version specific handling of the returned tuple while maintaining
compatibility with earlier releases of Gtk+.

References:

1.  https://github.com/GNOME/gtk/commit/a3a5cf1087278e3e727a74c75f2532bcb14ddca6