Fix warning on entry focus to entry
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Chat.activity/activity.py", line 505, in _entry_focus_in_cb
    self._hide_smiley_window()
  File "/usr/share/sugar/activities/Chat.activity/activity.py", line 659, in _hide_smiley_window
    self._smiley_window.hide()
AttributeError: 'Chat' object has no attribute '_smiley_window'

Regression introduced by 0f09a26681f01b484efa67ebda06e869c44f5e3d, as
the attribute may not exist.